name: CI with Kover & PR Comment

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  run-tests:
    name: Run Tests with Kover
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test koverHtmlReport koverXmlReport

      - name: Upload Kover HTML coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kover-html-report
          path: build/reports/kover/html/

      - name: Publish Unit Test Results as PR comment
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: build/test-results/test/TEST-*.xml
